services:
  - type: web
    name: spendsense-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: python seed.py && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SECRET_KEY
        generateValue: true
      - key: CORS_ORIGINS
        value: "*"
      - key: DATABASE_URL
        fromDatabase:
          name: spendsense-db
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false

databases:
  - name: spendsense-db
    databaseName: spendsense
    user: spendsense
    plan: free
